apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: observatoria.observatorium
spec:
  group: observatorium
  names:
    kind: Observatorium
    listKind: ObservatoriumList
    plural: observatoria
    singular: observatorium
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Observatorium is the Schema for the observatoria API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ObservatoriumSpec defines the desired state of Observatorium
          properties:
            thanos:
              description: Thanos Spec
              properties:
                image:
                  description: Thanos Image name
                  type: string
                querierreplicas:
                  description: Number of instances to deploy for a Thanos querier.
                  format: int32
                  type: integer
                tag:
                  description: Tag of Thanos sidecar container image to be deployed.
                    Defaults to the value of `version`. Version is ignored if Tag
                    is set.
                  type: string
                version:
                  description: Version describes the version of Thanos to use.
                  type: string
              required:
              - image
              - tag
              type: object
          required:
          - thanos
          type: object
        status:
          description: ObservatoriumStatus defines the observed state of Observatorium
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
